trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build job
    steps:
    - script: |
        echo "Install dependencies"
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        echo "Run tests"
        # Add commands to run your tests here
      displayName: 'Run tests'

- stage: Deploy
  displayName: Deploy stage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploy to Azure App Service"
              # Add your deployment scripts here
            displayName: 'Deploy to Azure App Service'
