name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6' 

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Zip the application for deployment
      run: zip -r deploy.zip . -x "*.git*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'foxai' # Replace with your Azure App Service name
        slot-name: 'production' # Adjust if deploying to a specific slot
        publish-profile: ${{TvwyYc2xJApXladautrkgyPKygXX27oFQT1haoWEeb4DFWputlXcvpA2CgM4 }} # Set your Azure publish profile as a GitHub secret
        package: deploy.zip
