name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:  # Define your environment variables here
      DB_CONNECTION_STRING: '{
        "user": "Giovanni",
        "password": "Foxai2024",
        "host": "foxaidbvsflex.postgres.database.azure.com",
        "port": 5432,
        "database": "foxaidbflex"
      }'
      OPENAI_API_KEY: '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'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Zip the application for deployment
      run: zip -r deploy.zip . -x "*.git*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'foxai' # Replace with your Azure App Service name
        slot-name: 'production' # Adjust if deploying to a specific slot
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_814E5FD1DC324511B8990AD3799A98A9 }}
        package: deploy.zip
